### ISSUE TITLE
TableNotFoundException, no such table: oc_maps_apikeys

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/maps#131]
Got this on enabling the Maps app just now:

```
Type : Doctrine\DBAL\Exception\TableNotFoundException
Code : 0
Message : An exception occurred while executing 'SELECT * FROM "oc_maps_apikeys" WHERE "user_id" = ?': SQLSTATE[HY000]: General error: 1 no such table: oc_maps_apikeys
Fichier : /home/jan/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php
Ligne : 58

Trace
#0 /home/jan/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /home/jan/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM "...')
#2 /home/jan/owncloud/lib/private/db/connection.php(162): Doctrine\DBAL\Connection->prepare('SELECT * FROM "...')
#3 /home/jan/owncloud/lib/private/appframework/db/db.php(70): OC\DB\Connection->prepare('SELECT * FROM `...', NULL, NULL)
#4 /home/jan/owncloud/lib/public/appframework/db/mapper.php(232): OC\AppFramework\Db\Db->prepareQuery('SELECT * FROM `...', NULL, NULL)
#5 /home/jan/owncloud/lib/public/appframework/db/mapper.php(280): OCP\AppFramework\Db\Mapper->execute('SELECT * FROM `...', Array, NULL, NULL)
#6 /home/jan/owncloud/lib/public/appframework/db/mapper.php(347): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)
#7 /home/jan/owncloud/apps/maps/db/apikeymapper.php(32): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM `...', Array)
#8 /home/jan/owncloud/apps/maps/controller/pagecontroller.php(65): OCA\Maps\Db\ApiKeyMapper->findByUser('jan')
#9 [internal function]: OCA\Maps\Controller\PageController->index()
#10 /home/jan/owncloud/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)
#11 /home/jan/owncloud/lib/private/appframework/http/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Maps\Controller\PageController), 'index')
#12 /home/jan/owncloud/lib/private/appframework/app.php(110): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Maps\Controller\PageController), 'index')
#13 /home/jan/owncloud/lib/private/appframework/routing/routeactionhandler.php(45): OC\AppFramework\App::main('PageController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#14 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#15 /home/jan/owncloud/lib/private/route/router.php(273): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#16 /home/jan/owncloud/lib/base.php(873): OC\Route\Router->match('/apps/maps/')
#17 /home/jan/owncloud/index.php(39): OC::handleRequest()
#18 {main}
```

Breaks the app. Any idea @v1r0x @Henni?

**Comment by v1r0x** [comment]
I added a new table, but didn't increase the version in `info.xml`. @Henni and I decided to increase the version right before the release.

**Comment by jancborchardt** [comment]
Ah, ok. I guess it would be good to jump to 0.1.0 soon because then we can just increase the patch version any time it’s needed.

**Comment by v1r0x** [comment]
@jancborchardt Definitely. Still trying to fix the POI stuff.
